### PR TITLE
Add GUID key generation and part key value preservation

### PR DESCRIPTION
**Pull request by mjstrasser**
These changes duplicate those in Olingo OData2:

https://issues.apache.org/jira/browse/OLINGO-1011
https://issues.apache.org/jira/browse/OLINGO-1014

### CODE REVIEW

**Comment by mjstrasser** [comment]
Hey @mibo

I wanted to include only the first two commits in this pull request. I didn’t know that GitHub would add more commits after I created the request. Please disregard commit 1e3859d until I figure out why the metadata tests are failing.

Thanks
Michael

**Comment by mibo** [comment]
Hi Michael,

Sorry, I pushed the change already I have only forgot to write it in the
JIRA Issue.
But no problem, just attach another patch when you found and fixed the root
cause.

Best Regards, Michael


Am 31. August 2016 um 03:08:19, Michael Strasser (notifications@github.com)
schrieb:

Hey @mibo <https://github.com/mibo>

I wanted to include only the first two commits in this pull request. I
didn’t know that GitHub would add more commits after I created the request.
Please disregard commit 1e3859d
<https://github.com/mibo/janos/commit/1e3859db9a787a3a7e44664b2b73e5739ef1fdb4>
until I figure out why the metadata tests are failing.

Thanks
Michael

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mibo/janos/pull/11#issuecomment-243629432>, or mute the
thread

**Comment by mjstrasser** [comment]
Hi Michael

I am confused! Your comment appears to be about my patches to Olingo, not this pull request to Janos. 

My first two GitHub commits were to Janos to align it with my changes to Olingo. I wanted the request to include only those commits, not later enhancements to function import processing.

Regards
Michael

**Comment by mibo** [comment]
Hi Michael,

Sorry, I was a little bit confused by myself  ;o)
As suggested by you I will only merge `ac67db6` and `6b9b243`.
And Thanks for the contribution.

Best Regards, Michael

**Comment by mibo** [comment]
Hi Michael,

I hope [this pull request](https://github.com/mibo/janos/pull/12) is what you currently want.
If yes, I would close this and merge #12 .

Best Regards,
Michael

**Comment by mjstrasser** [comment]
Request #12 does what I want. Closing this one now.

**Pull request closed without merging**
